### ISSUE TITLE
Job locking

### ISSUE THREAD

**Issue by lpil** [jfischoff/postgresql-queue#7]
Hello!

Thanks for this lib :)

I was reading the docs and the source and I think that the example given (see below) isn't up to date.
 
```haskell
  forever $ do
    -- Attempt get a payload or block until one is available
    payload <- lock conn

    -- Perform application specifc parsing of the payload value
    case fromJSON $ pValue payload of
      Success x -> sendEmail x -- Perform application specific processing
      Error err -> logErr err

    -- Remove the payload from future processing
    dequeue conn $ pId payload
```

The `lock` function seems to have been removed. What's the right way to use this now?

Thanks,
Louis

**Comment by jfischoff** [comment]
It's not up to date. Will update when I find this "free time" I've heard so much about. PRs welcome!
